# Generated by Django 5.0.3 on 2024-03-22 08:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.EmailField(max_length=100)),
                ("company", models.CharField(max_length=50)),
                ("nif", models.CharField(max_length=50)),
                ("clave_id", models.CharField(max_length=12)),
                ("address", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=250, null=True),
                ),
                ("media", models.ImageField(upload_to="uploads/product/")),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "reference",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "manufacturer_reference",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "min_order_qty",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "brand",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "hashtag",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "dimensions",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "url",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "visible",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "address",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("date", models.DateField(default=datetime.datetime.today)),
                ("status", models.BooleanField(default=False)),
                (
                    "customer_reference",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
    ]
