# Generated by Django 5.0.3 on 2024-03-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_profile_old_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_min_qty",
            field=models.IntegerField(default=0),
        ),
    ]
