# Generated by Django 5.0.3 on 2024-03-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_stock_min_qty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stock_min_qty",
            new_name="stock_min_qty_alert",
        ),
        migrations.RemoveField(
            model_name="product",
            name="dimensions",
        ),
        migrations.AddField(
            model_name="product",
            name="dim_debt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="dim_height",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="dim_weight",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="dim_width",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=250000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_order_qty",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="product",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.CharField(blank=True, default="", max_length=160, null=True),
        ),
    ]
