# Generated by Django 5.0.3 on 2024-03-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_rename_stock_min_qty_product_stock_min_qty_alert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=200)),
                ("service_code", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="category",
            name="name",
        ),
        migrations.AddField(
            model_name="category",
            name="category_allowed_groups",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="category_description",
            field=models.CharField(blank=True, default="", max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="category_image",
            field=models.ImageField(null=True, upload_to="uploads/category/"),
        ),
        migrations.AddField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="category_parent",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="category_title",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="category_url",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="category_visible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="media",
            field=models.ImageField(null=True, upload_to="uploads/product/"),
        ),
    ]
