# Generated by Django 5.0.3 on 2024-03-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_service_remove_category_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_name",
            new_name="name",
        ),
    ]
