# Generated by Django 5.0.3 on 2024-03-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_rename_category_name_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_allowed_groups",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/category/"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_parent",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
