# Generated by Django 5.0.3 on 2024-03-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_remove_product_category_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.category"
            ),
        ),
    ]
