# Generated by Django 5.0.3 on 2024-03-28 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("store", "0012_discount_alter_product_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="discount_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_description",
            field=models.CharField(
                blank=True, default="", max_length=250000, null=True
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_fix_or_percentage",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Loyalty", "Loyalty"),
                    ("Volume", "Volume"),
                    ("Credit", "Credit"),
                    ("Product type", "Product type"),
                    ("Promotion", "Promotion"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_free_shipping",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_min_order_value",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_priority",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_scope_category",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="store.category"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_scope_product",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.product"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_scope_user",
            field=models.ManyToManyField(
                blank=True, related_name="users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_scope_user_group",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_stop_other_discounts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Loyalty", "Loyalty"),
                    ("Volume", "Volume"),
                    ("Credit", "Credit"),
                    ("Product type", "Product type"),
                    ("Promotion", "Promotion"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_use_limit",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_validity_end",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_validity_start",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_allowed_groups",
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50, null=True)),
                ("brand_visible", models.BooleanField(default=False)),
                (
                    "brand_description",
                    models.CharField(
                        blank=True, default="", max_length=2500, null=True
                    ),
                ),
                (
                    "brand_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/brand/"
                    ),
                ),
                (
                    "brand_title",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "brand_url",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "brand_allowed_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="brand_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_scope_brand",
            field=models.ManyToManyField(
                blank=True, related_name="brands", to="store.brand"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="category_allowed_groups",
            field=models.ManyToManyField(
                blank=True, related_name="user_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
