# Generated by Django 5.0.3 on 2024-03-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_discount_discount_active_discount_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="discount_use_limit_per_user",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
