# Generated by Django 5.0.3 on 2024-03-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_discount_discount_use_limit_per_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="brand_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
