# Generated by Django 5.0.3 on 2024-03-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_alter_brand_brand_url_alter_category_category_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_collect",
            field=models.CharField(
                blank=True,
                choices=[("Pickup", "Pickup"), ("Delivery", "Delivery")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_deposit",
            field=models.CharField(
                blank=True,
                choices=[("Pick Up", "Pick Up"), ("DropOff", "DropOff")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Orona", "Orona"),
                    ("Otis", "Otis"),
                    ("Microvision", "Microvision"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_note",
            field=models.TextField(blank=True, default="", max_length=10000, null=True),
        ),
    ]
