# Generated by Django 5.0.3 on 2024-03-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_customer_clave_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name_plural": "Brands"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ManyToManyField(
                blank=True, related_name="brand", to="store.brand"
            ),
        ),
    ]
