# Generated by Django 5.0.3 on 2024-03-28 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_alter_brand_options_remove_product_brand_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="store.brand",
            ),
        ),
    ]
