# Generated by Django 5.0.3 on 2024-03-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_discountchoice_alter_discount_discount_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Loyalty", "Loyalty"),
                    ("Volume", "Volume"),
                    ("Credit", "Credit"),
                    ("Product type", "Product type"),
                    ("Promotion", "Promotion"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
