# Generated by Django 5.0.3 on 2024-03-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_alter_discount_discount_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiscountChoice",
        ),
    ]
