# Generated by Django 5.0.3 on 2024-04-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_alter_discount_discount_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name_plural": "brands"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
