# Generated by Django 5.0.3 on 2024-04-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_alter_brand_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="company",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
