# Generated by Django 5.0.3 on 2024-04-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_profile_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="service_note",
            new_name="service_description",
        ),
        migrations.AddField(
            model_name="service",
            name="service_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
