# Generated by Django 5.0.3 on 2024-03-28 15:16

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_order_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_name", models.CharField(max_length=100)),
                ("status_visible", models.BooleanField(default=False)),
                (
                    "status_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=25, samples=None
                    ),
                ),
                ("status_send_email", models.BooleanField(default=False)),
                ("status_email_template", models.CharField(max_length=100)),
                ("status_paid", models.BooleanField(default=False)),
                ("status_sent", models.BooleanField(default=False)),
                ("status_delivered", models.BooleanField(default=False)),
                ("status_attach_file", models.BooleanField(default=False)),
                ("status_file_url", models.URLField()),
                ("status_hide_for_user", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "OrderStatuses",
            },
        ),
    ]
