# Generated by Django 5.0.3 on 2024-05-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_order_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_reference",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
