# Generated by Django 5.0.3 on 2024-03-28 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_remove_orderitem_order_order_order_items_and_more"),
        ("store", "0015_alter_brand_brand_url_alter_category_category_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_items",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="store.order"
            ),
        ),
    ]
