# Generated by Django 5.0.3 on 2024-03-28 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0013_alter_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.shippingaddress",
            ),
        ),
    ]
