# Generated by Django 5.0.3 on 2024-03-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0014_order_order_shipping_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
    ]
