# Generated by Django 5.0.3 on 2024-03-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0015_remove_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
