# Generated by Django 5.0.3 on 2024-03-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0016_orderitem_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="total",
        ),
    ]
